Update cl.xml for new vendor IDs in vk.xml
KhronosGroup/OpenCL-Docs pull request #506
Opened 2020-11-30 16:10 UTC by franz

This depends on PR to [add](https://github.com/KhronosGroup/Vulkan-Headers/pull/169) PoCL vendor ID in Vulkan headers.

2020-11-30 16:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenCL-Docs?pullRequest=506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenCL-Docs?pullRequest=506) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenCL-Docs?pullRequest=506) it.</sub>

2020-11-30 16:52 UTC, EwanC requested changes

2020-11-30 16:52 UTC, EwanC commented on xml/cl.xml
> -        <enum value="0x10004" name="CL_KHRONOS_VENDOR_ID_CODEPLAY" comment="Codeplay Software Ltd."/>
We're using this vendor ID, looks like it's getting removed. Should PoCL be getting added rather than removing Codeplay?

2020-11-30 17:30 UTC, bashbaug requested changes
I think you'll want a Vulkan-Docs PR first, to reserve the vendor ID enum.  See, for example, https://github.com/KhronosGroup/Vulkan-Docs/pull/1168, which reserved the Codeplay enum.

Note that this should be a Vulkan-Docs PR and not a Vulkan-Headers PR.

We should merge this PR after the Vulkan-Docs PR is merged.  Thanks!

2020-12-01 09:17 UTC, EwanC commented on xml/cl.xml
> -        <enum value="0x10004" name="CL_KHRONOS_VENDOR_ID_CODEPLAY" comment="Codeplay Software Ltd."/>
Looks good now, thanks

2020-12-01 20:11 UTC, alycm reviewed
LGTM, needs the VK XML PR to merge first to reserve the value: https://github.com/KhronosGroup/Vulkan-Docs/pull/1411

Both PRs just need the CLA to be agreed.

2020-12-04 10:21 UTC, EwanC approved these changes
Accompanying https://github.com/KhronosGroup/Vulkan-Docs/pull/1411 is merged now

2020-12-04 16:51 UTC, bashbaug approved these changes
LGTM

2020-12-04 16:51 UTC, merged