[WIP] Define upcoming FPGA extension in XML to avoid creation of orphan enums
KhronosGroup/OpenCL-Docs pull request #773
Opened 2022-03-16 18:23 UTC by mkinsner

Test built headers using https://github.com/KhronosGroup/OpenCL-Headers/pull/161

2022-04-12 23:06 UTC, pcolberg requested changes

2022-04-12 23:06 UTC, pcolberg commented on xml/cl.xml
> +            <param><type>void</type>*               <name>ptr</name></param>
Analogous with [clEnqueueWriteBuffer](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueWriteBuffer.html):
```suggestion
            <param>const <type>void</type>*               <name>ptr</name></param>
```

2022-04-13 00:10 UTC, pcolberg approved these changes

2022-04-29 19:08 UTC, bashbaug approved these changes
LGTM, verified that the header generation script and the specs built fine after this change.

2022-04-29 19:08 UTC, merged