cl_khr_external_semaphore_khr
KhronosGroup/OpenCL-Docs pull request #939
Opened 2023-06-09 20:01 UTC by lakshmih

Add clImportSemaphoreSyncFD API call.  Sync fd semaphores must re-import the sync_fd after every wait.  Add an API call to make this re-import possible, without creating a new OpenCL semaphores.  See issue #888.

2023-06-09 20:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenCL-Docs?pullRequest=939) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenCL-Docs?pullRequest=939) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenCL-Docs?pullRequest=939) it.</sub>

2023-07-15 01:35 UTC, bcalidas commented
That makes sense. We will rename to clReimportSemaphoreSyncFdKHR.

2023-08-22 01:24 UTC, bcalidas commented
Regarding the discussion around whether the usage clImportSemaphore API call should be required for importing an external semaphore payload  - we prefer the current approach of importing the external semaphore payload when the semaphore is created using clCreateSemaphoreWithProperties. This allows us to have a clean description of  external semaphore state soon as it is created. Our recommendation is that usage of   clImportSemapore be considered as a convenience as opposed to a requirement.

2023-08-29 18:11 UTC, bashbaug commented on ext/cl_khr_external_semaphore.asciidoc
> +To import a handle of type {CL_SEMAPHORE_HANDLE_SYNC_FD_KHR} into an existing semaphore, call the function
Discussed in the August 29th teleconference.  I think either:

1. This sentence is stale and should be updated to include all handle types (it sounded like this was the intent).
2. Or, we need to define an error code when this API is used with a non-SYNC_FD handle type.

2023-09-01 21:54 UTC, bashbaug reviewed
A few other follow-up questions about this feature:

1. What happens if there are outstanding signal or wait operations on the semaphore that is being re-imported?  Should these signal or wait operations operate on the previous semphore handle (the one that was imported when the enqueue call was made), or the new semaphore handle (the one that was imported when the command executes), or should this case be implementation-defined or undefined behavior?
2. Pending resolution of the discussion on #945, what should happen to any exported handles from a semaphore that has been re-imported?  Are they invalid?  If they are valid, do they refer to the "old" semaphore, or to the "new" semaphore?
3. I'm not sure if this needs to be documented explicitly in the spec or not, but just to confirm: calling clImportSemaphoreKHR does not modify the reference counts on the semaphore object, correct?

2023-09-05 11:59 UTC, nikhiljnv reviewed
Have left some comments based on initial review.

2023-09-05 11:59 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +_import_props_  Must be `NULL`.  Reserved for future use.
Do we have any insights into what properties we may want to pass here?
May be we can fold handle_type into import_props and keep it consistent with clCreateSemaphoreWithPropertiesKHR?

2023-09-05 11:59 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +The semaphore _sema_object_ must have originally imported a handle of type _handle_type_.
Do we need handle_type and handle_size in that case? The handle_type and size associated with sema_object should be available from sema_object itself.

2023-09-05 11:59 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +Calling {clImportSemaphoreKHR} is equivalent to destroying _sema_object_ and re-creating it with the original _sema_props_
Are implementations strictly required to destroy sema_object and recreate it by associating with new handle? Or just closing earlier handle reference and associating new handle reference with sema_object good enough?

2023-09-05 11:59 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +_sema_object_ specifies a valid semaphore object with importable properties.
Do we strictly need to pass handle value at the time of import if we can associate it with this new API at a later point?
We don't need to disallow, but would it make sense to make it optional or allow the handle value to be NULL?

2023-09-05 11:59 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +include::{generated}/api/protos/clImportSemaphoreKHR.txt[]
If the intent is to change some of the semaphore properties passed at the time of clCreateSemaphoreKHR API (associated handle_value in this case), would it make sense to rename this API to something like clSetSemaphorePropertiesKHR? May be it is easier to reuse and extend it to other cases if needed in the future?

2023-09-05 12:01 UTC, nikhiljnv commented
> What happens if there are outstanding signal or wait operations on the semaphore that is being re-imported? Should these signal or wait operations operate on the previous semphore handle (the one that was imported when the enqueue call was made), or the new semaphore handle (the one that was imported when the command executes), or should this case be implementation-defined or undefined behavior?

+1 to Ben's comments.

2023-09-11 15:04 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +include::{generated}/api/protos/clImportSemaphoreKHR.txt[]
Just noting down the summary of discussion last week -
This is not a preferred path in general for OpenCL objects.
We do not want OpenCL objects to be modifiable via direct Set APIs for good reason

2023-09-13 22:29 UTC, bcalidas commented
Regarding 
1) What happens if there are outstanding signal or wait operations on the semaphore that is being re-imported? Should these signal or wait operations operate on the previous semphore handle (the one that was imported when the enqueue call was made), or the new semaphore handle (the one that was imported when the command executes), or should this case be implementation-defined or undefined behavior?

>>> If a semaphore has a pending signal and clReleaseSemaphore is called, then the effect is likely implementation defined. We should put this clarification in the base spec.  With the latest version of the spec, the semaphore is safe to resignal/reimport as soon as WaitSemaphore returns. Therefore we only need to worry about the situation where the semaphore is released/re-imported  without WaitSemaphore ever having been called.

2023-09-13 22:37 UTC, bcalidas commented
Regarding
2) Pending resolution of the discussion on https://github.com/KhronosGroup/OpenCL-Docs/issues/945, what should happen to any exported handles from a semaphore that has been re-imported? Are they invalid? If they are valid, do they refer to the "old" semaphore, or to the "new" semaphore?
In this situation, the semaphore logically would need to be-exported from OpenCL. Once OpenCL re-imports the semaphore handle , the externally exported handle would continue pointing to the old semaphore. Hence the need for re-export. This is also consistent with what you would expect if you released the semaphore and created a new one via import.

2023-09-26 05:23 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +    void *handle_ptr);
Any specific reason to pass handle_ptr as a separate parameter and not make it one of the props just like supported by clCreateSemaphoreKHR?

2023-10-24 19:08 UTC, bcalidas commented
Based on discussions around export of imported semaphores which we have decided is not permitted (  (https://github.com/KhronosGroup/OpenCL-Docs/issues/945)
and clarification of Release Semaphore Behavior ( https://github.com/KhronosGroup/OpenCL-Docs/pull/969 ) we believe that potential  behavior  issues relating to semaphore re-import have been resolved.

The next steps are to finalize the clImportSemaphoreKHR() function name and function signature.

2023-11-14 18:28 UTC, nikhiljnv commented
As discussed in memory subgroup call on November 14, 2023, agree to move the API to cl_khr_external_semaphore_sync_fd.

2023-11-20 23:24 UTC, bcalidas commented
Please review the latest changes. The semaphore re-import command has been moved into the sync fd extension

2023-11-21 18:41 UTC, kpet requested changes
This change ought to bump the extension spec number

2023-11-21 18:43 UTC, paulfradgley commented
Looks good to me too.

2023-11-21 22:01 UTC, joshqti commented
I pushed a commit to advanced the extension number.

2023-11-28 11:08 UTC, nikhiljnv commented
Is the change ready to go? Or are there any reviews pending? Also, we need to resolve the conflicts on TOT.

2023-11-28 17:48 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +typedef cl_properties cl_semaphore_import_properties_khr;
Should this be renamed to cl_semaphore_reimport_properties_khr?
Are these going to be distinct from cl_semaphore_properties_khr that can be passed at the time of clCreateSeamphoreKHR possibly supporting initial import?

2023-11-28 18:12 UTC, nikhiljnv commented on ext/cl_khr_external_semaphore.asciidoc
> +typedef cl_properties cl_semaphore_import_properties_khr;
Can be merged after rename to cl_semaphore_reimport_properties_khr, version update and conflict resolution.

2023-11-28 18:12 UTC, bashbaug reviewed
LGTM, once the properties are renamed (to reimport) and the version conflict is resolved (the new version should be 0.9.2 now).  Ping me once these are fixed and I'll do a final approval and merge.

2023-11-29 13:03 UTC, nikhiljnv approved these changes
LGTM.

2023-11-30 19:00 UTC, bashbaug approved these changes
LGTM.  I believe @kpet's requested changes have been addressed, so we're OK to merge this.

2023-11-30 19:01 UTC, merged